events {}

http {
    upstream image_service {
        server image-service:8080;
    }

    upstream journey_service {
        server journey-service:8080;
    }

    server {
        listen 80;

        # route to image-service
        location /images/ {
            proxy_pass http://image_service/;
        }

        # route to journey-service
        location /journeys/ {
            proxy_pass http://journey_service/;
        }
    }
}
