events {}

http {
    upstream image_service {
        server image-service:8080;
    }

    upstream journey_service {
        server journey-service:8080;
    }

    upstream ui {
        server ui:3000;
    }

    server {
        listen 80;

        location /images/ {
            proxy_pass http://image_service/;
        }

        location /journeys/ {
            proxy_pass http://journey_service/;
        }

        location /ui/ {
            proxy_pass http://ui/;
        }
    }
}
